blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/servinoo/servinoo-web-application/wiki
    about: Check our documentation for detailed guides and FAQ
  - name: 💬 Discussions
    url: https://github.com/servinoo/servinoo-web-application/discussions
    about: Join our community discussions for general questions and ideas
  - name: 🔒 Security Issues
    url: https://github.com/servinoo/servinoo-web-application/security/policy
    about: Please report security vulnerabilities privately